[package]
name = "day-13"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day-13"
doctest = false

[dependencies]
utils = { path = "../utils" }
pest = "2.7.15"
pest_derive = { version = "2.7.15"}
